# 野良パッケージで不用意に install しちゃったとき用のガードとして。
# 基本的には各リポジトリの bunfig.toml で明記している。
# you can configure in global bunfig for which command
# 	https://github.com/oven-sh/bun/blob/main/src/cli.zig
# 	-> grep "readGlobalConfig"
[install]
minimumReleaseAge = 259200
[install.security]
#scanner = "@socketsecurity/bun-security-scanner"
scanner = "@bun-security-scanner/osv"
